<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portafolio Sarita - evaluación</title>
    <link rel="stylesheet" href="../../styles/header.css">
    <link rel="stylesheet" href="../../styles/evaluacion.css">
    <link rel="stylesheet" href="../../styles/reset.css">
</head>
<body>
    <div class="background_2">
        
        <?php include "../../includes/header.php"; ?>

        <div class="content">
            <div class="photo">
                <div class="evaluator_photo">
                    <img src="../../assets/evaluadores/humberto.jpeg " alt="">
                </div>
                <div class="mantel_photo">
                    <img src="../../assets/mantel.png" alt="Mantel">
                    <div class="mantel_text">
                        <p>
                            Humberto es, para mí, guía y maestro. guía porque me acogió cuando estaba asustada y me sentía pequeña, y me enseñó todo de lo que yo era capaz. y maestro porque lo observo, y lo observo con la admiración con la que se observa a alguien cómo él, que ha encontrado su verdad en la danza, y se ha ganado un merecido espacio a punta de esfuerzo y de persistencia, de no abandonarse a sí mismo nunca. <br>
                            Beto, te agradezco por enseñar con tanta confianza en las capacidades e impulsos de tus alumnos. por acompañarme y creer en mí, cuando yo me sentía cómo una tormenta. tu enseñanza fue como una luz en mitad de una noche en el océano, y por eso siempre te voy a agradecer.
                        </p>
                    </div>
                </div>
            </div>
            <p>
                La Carrera de Artes Escénicas de la Pontificia Universidad Javeriana tiene tres ejes transversales que son el estudio del performance, la improvisación y la educación somática, todas ellas pero particularmente esta última, nos permiten visualizar a nuestro futuro egresado como un artista integral que tiene como meta el desarrollo de sus capacidades creativas más allá de la ejecución puramente para la danza o el teatro, sino más bien a uno que se destaca por su capacidad de ser un investigador permanente de sí mismo, que logra escuchar(se) en sus impulsos más personales e íntimos y transforma sus propias debilidades en oportunidades para conocerse mejor y desde ahí construir un discurso sólido, conmovedor y potente. <br>  
                Cuando pienso en <span class="bld">Sarah Juliana Rodríguez</span> me doy cuenta de que ha sido de esas estudiantes persistentes, proactivas y que han hecho de su proceso un camino a veces duro, pero plagado de oportunidades que han sabido aprovechar al máximo. Y aunque estos procesos de formación en las artes escénicas pueden ser a veces difíciles, esa constante confrontación consigo misma, hizo que una persona como <span class="bld">Sarah</span> se confronte y luche con sus propias creencias, sus propios miedos y bloqueos, para de esa manera convertirse en una artista escénica mucho más sólida, fuerte, creativa y sobre todo más comprometida con sus capacidades expresivas; más allá del conocimiento que podía traer de la danza en su propio cuerpo, <span class="bld">Sarah</span> se ha dado el espacio para seguir descubriendo, “para renovar la vida en su cuerpo” como dice ella misma en su declaración de artista, para “…bailar con todos los cuerpos que ha sido…” y todos los que empezará a ser, agregaría yo en este momento. <br>  
                Es notorio que span.bld trae una formación previa en la danza, tanto en ballet como en jazz, esto podría de alguna manera facilitar su camino en ciertas materias, sobre todo las técnicas, pero ella siempre se adentra en la aventura de su formación con gran hambre de aprendizaje, con la avidez de conocimiento que tiene un niño, con curiosidad se mide a los nuevos conceptos o estilos con un alto nivel de exigencia y autocrítica, que si bien a veces podía jugar en su contra, siempre sabe cómo sacar una sonrisa en su cuerpo y avanzar sin que la crítica o la dificultad se vuelvan un obstáculo sino más bien, de manera muy somática, se conviertan en puerta de oportunidad, siempre al lado de la perseverancia y la disciplina. <br>
                Para mí, como profesional de las artes escénicas, más que como profesor, siento aprecio y cercanía con estudiantes como <span class="bld">Sarah</span>, que se van dando a conocer por la constancia, por el rigor y por su capacidad de ponerse metas altas y desafíos en el camino, con gran espíritu de superación. Poder observar esto en mis estudiantes es una forma de visualizar a mis futuros colegas y reconocer en esa beligerancia su enorme deseo de escuchar su cuerpo y al oficio teatral desde una perspectiva llena de “comprensión”, como nos señala Max Neef en el texto El Acto Creativo: “se aprende así de uno mismo, comprender es el primer acto creativo humano”. De esta forma se puede reafirmar el trabajo del estudiante hacia su profesionalización, porque da credibilidad a nuestro quehacer desde el estudio y las aulas. Estar abierto a esa verdad de nuestro cuerpo que sensibiliza y hace más perceptiva nuestra manera de estar presentes y evolucionar en el proceso, aprendiendo así, que será de esta forma siempre, a lo largo de toda la carrera profesional. <br>
                Para el año 2023 conocí a <span class="bld">Sarah</span> porque tuve la oportunidad de hiciera parte del elenco de ejecutantes-creadores del Ensamble Interdisciplinario de Danza Contemporánea al que titulamos “In-nOcenS”, donde tratamos el tema de la explotación sexual y comercial de niños, niñas y adolescentes (ESCNNA), un tema complejo, duro y que fue tratado de manera interdisciplinar haciendo uso de varios estilos de movimiento, acciones físicas, video mapping y danza contemporánea. Durante todo el proceso de creación ella dio muestra de tener un excelente desarrollo técnico, pero sobre todo de una enorme convicción y generosidad del papel que tiene como artista al ser un activo social que crea reflexión y busca ser crítica con los acontecimientos actuales. Fue muy fácil trabajar con ella, ya que su actitud y manera de estar presente en el desarrollo de la pieza fue muy fluido y proactivo, fue atenta con el material coreográfico que se le propuso y muy exigente en su nivel de calidad, es una artista colaborativa, con una actitud positiva con el proceso en cada una de sus etapas, tanto en el trabajo de mesa, como en la creación misma. Con ella se puede tener la tranquilidad de que su resultado estará marcado por la excelencia ya que es lo suficientemente autocrítica y rigurosa consigo misma para asumir correcciones, pautas y valoraciones de su trabajo, pero además es muy buena colaboradora, sabe muy bien darle espacio al trabajo en equipo y reconocer que su éxito es el de todo el proyecto. <br>
                En el siguiente semestre, llegó al Laboratorio de Composición Coreográfico, en esta clase se busca que el estudiante se sumerja en su propia historia e indague desde allí sus impulsos creativos. En esta clase antes de hacer coreografía en tercera persona, se debe hacer corpografía en primera persona. Con este principio de investigación se establece una comunicación con el estudiante donde se puede exaltar su capacidad de crear dramaturgia del movimiento desde su fuero más íntimo, y buscar en sus miedos y vulnerabilidades, con la posibilidad de construir un discurso consistente que pueda ser defendido en el escenario con mucha más certeza y precisión. En esta área pude notar la gran sensibilidad de <span class="bld">Sarah</span>, ver cómo iba dando sentido y definiendo cuáles son sus verdaderas herramientas creativas de investigación para la puesta en escena, y con ello sus inquietudes como creadora. Este proceso puede ser un espacio revelador y al mismo tiempo intimidante, ya que estamos acostumbrados a crear desde afuera, desde los referentes externos, desde los estilos de danza o movimiento y no necesariamente desde nosotros y nuestras percepciones más profundas, tendemos a obviar lo que sentimos o pensamos o creemos, <span class="bld">Sarah</span> a lo largo de ese semestre se tomó el riesgo y se adentró a su mundo interior sin miramientos y con determinación. <br>
                Para el primer semestre del 2024 <span class="bld">Sarah Juliana</span> matriculó dos clases técnicas conmigo: Danza Moderna compartida con Ballet y Técnica de Jazz compartida con Tap.  En estas dos materias pude observar con mayor detenimiento su desarrollo técnico y su capacidad de ser detallista y minuciosa con su trabajo, también de observar su gozo y disfrute a la hora de bailar e incluso su expresividad más teatral, también comprender de una manera más clara y palpable los alcances que tiene este proceso de formación que se ofrece en Escénicas de la Javeriana, en donde es sumamente importante que el estudiante se convierta en un investigador de sí mismo todo el tiempo, no está de más decir que <span class="bld">Sarah</span> tuvo siempre una excelente actitud y demostró el interés profundo que sienta de mejorar día a día su trabajo de ejecución técnica, y la alegría además de constatar de que en realidad si es posible encontrar una riqueza en la repetición técnica, descubrir claridad a la hora del entrenamiento sin perder de vista nuevas cualidades y la interpretación pro escénica.  <br>
                <span class="bld">Sarah Juliana Rodríguez</span> es un muy buen ejemplo de que la buena actitud, la constancia y la disciplina son la clave para llegar tan lejos como se quiere, no importa si estás en el estudio técnico, en la creación coreográfica, en el ensayo o el escenario. Ella siempre supo sacar el mejor provecho de cada una de esas instancias sabiendo como focalizar su carácter, enfocar sus anhelos y ofrecer lo mejor de sí para lograr ese alto nivel que tiene siempre como objetivo. Quiero ahora aprovechar para agradecerte que me hayas invitado a ser parte de tu portafolio, ya que me siento feliz de haber podido compartir contigo parte de tu evolución como bailarina y artista escénica. Sigue trabajando con esa misma pasión y calma para mantener vivos todos los deseos que has puesto en la danza, que tengas una maravillosa vida profesional y que este amor por la escena te lleve a lugares que tal vez aún no has imaginado. <br>
            </p>
            <hr>
            <p>
                <span class="bld">HUMBERTO CANESSA ULLOA</span> <br> 
                Profesor Cátedra Carrera de Artes Escénicas <br> 
                Pontifica Universidad Javeriana de Bogotá  <br>
            </p>
        </div>
    </div>
    <script src="./../../assets/js/main.js"></script>
</body>
</html>